const weeklyTechnicalBriefs = [
  "Begin by running Python interactively and then saving the same statements in a script. Python values have types such as int, float, str, bool, and NoneType; variables are names bound to those values. Arithmetic operators produce numeric results, while strings support indexing, slicing, concatenation, and formatted output. input() always returns text, so conversion belongs at the boundary. For a target normalizer, collect one line, strip surrounding whitespace, reject an empty value, and print a structured preview before writing anything.",
  "Conditionals select behavior using expressions that become True or False. Use if, elif, and else when branches are mutually exclusive, combine predicates with and, or, and not, and prefer direct membership tests over deeply nested comparisons. Imports make functions and constants from another module available; importing does not mean copying its source. This week, use ipaddress from the standard library to parse local target text and permit it only when it belongs to the declared lab network.",
  "Lists preserve ordered values and are suited to a queue of local inputs. A for loop consumes an iterable one item at a time; range produces a lazy arithmetic sequence, and while repeats only while its condition remains true. Termination must be obvious before writing a while loop. Build a wordlist cleaner by iterating over saved fixture lines, normalizing each value, using a set for uniqueness, and returning a sorted list so output remains deterministic.",
  "Dictionaries map unique keys to values and can nest lists or other dictionaries to represent targets and findings. JSON serializes compatible dictionaries and lists for storage or APIs. A virtual environment isolates project dependencies; pip installs packages into that environment. For the lab, read a local JSON configuration and saved API-response fixture, validate expected keys and types, transform it into your own schema, and export JSON. No live API credential is required.",
  "A function packages one responsibility behind parameters and a return value. Positional arguments are matched by order, keyword arguments by name, and default values should be immutable. Returning data keeps a function composable; printing is a user-interface side effect. Split the project into parse_input, validate_target, normalize_record, and render_report functions, then test each independently with normal, boundary, and invalid values.",
  "A class defines a new object type that combines state with behavior. __init__ establishes valid initial attributes, instance methods receive self, and each instance maintains its own state. Model Target, Observation, and Finding separately instead of placing every field into one growing dictionary. Constructors validate invariants; methods perform behavior that naturally belongs to the object; reporting remains in a separate component.",
  "Inheritance expresses an is-a relationship, while composition builds an object from collaborators and is usually easier to change. A collector interface can define collect(), with Linux and Windows implementations returning the same Observation shape. Prefer composition for hashing, redaction, and storage services so they can be replaced during tests. Never let a plug-in bypass the shared scope or safety policy.",
  "Exceptions separate successful results from failures that a caller can handle. Catch specific exceptions around the operation that may fail and preserve useful context. Use with when opening files so handles close reliably, specify UTF-8 for text, and use pathlib for cross-platform paths. A file organizer first computes a plan, displays it in dry-run mode, checks that every destination stays inside the workspace, and only then performs explicitly approved changes.",
  "An IPv4 address is 32 bits; CIDR combines an address with a prefix length that identifies the network portion. Python's ipaddress module understands hosts, networks, membership, and canonical formatting. Parse user input rather than splitting on dots, reject ambiguous targets, and require every address to be a member of an explicit lab allowlist before any connection attempt.",
  "TCP provides an ordered byte stream with connection state; UDP sends independent datagrams without delivery guarantees. A port identifies an application endpoint, not a vulnerability. Socket clients must set timeouts, close resources, distinguish refused connections from timeouts, and decode received bytes carefully. Limit tests to a short allowlist and a small declared port set in your local lab.",
  "DNS maps names to records through a distributed resolver system. A name may have A, AAAA, CNAME, MX, or TXT records, and answers can be cached according to TTL. Resolution failure, no record of a requested type, and a timeout are different outcomes. Store query name, record type, answer, resolver context, and timestamp so inventory results remain explainable.",
  "HTTP is a request-response protocol. A request has a method, target, headers, and optional body; a response has a status code, headers, and body. Status classes communicate broad outcomes but do not prove security. Set connection and read timeouts, follow redirects intentionally, bound body size, preserve TLS verification, and record only redacted request metadata.",
  "A URL contains a scheme, authority, path, query, and fragment. Percent encoding represents bytes in components, and different components have different parsing rules. Use urllib.parse instead of string concatenation. Normalize the hostname, remove fragments for server requests, preserve meaningful path boundaries, and recheck the resolved destination against scope before sending traffic.",
  "Headers carry HTTP metadata, cookies maintain state, and a session reuses connection and cookie context. Security attributes such as Secure, HttpOnly, and SameSite reduce specific cookie risks but must be interpreted in application context. Do not log session values. An auditor should report attribute presence and scope, not copy secrets or claim a vulnerability from one header alone.",
  "TLS authenticates endpoints and protects data in transit. Certificate validation checks trust, hostname, validity period, and chain; encryption without identity validation is insufficient. Keep verification enabled, record certificate metadata rather than private material, and handle expiration or hostname errors as structured findings. Never teach bypassing verification as the default fix.",
  "REST APIs use HTTP representations and often paginate large collections. Authentication credentials belong outside source code. A reliable client checks status codes, validates JSON shape, follows documented next links, respects Retry-After, uses bounded exponential backoff, and stops after a configured page or item limit. Idempotency determines whether retrying a request is safe.",
  "Threads can overlap blocking I/O because one thread can wait while another runs, but shared mutable data needs coordination. ThreadPoolExecutor bounds workers and returns Future objects that preserve results and exceptions. Do not create one thread per target. Keep result ordering deterministic, use individual timeouts, and collect failures as data rather than losing them in worker output.",
  "asyncio runs cooperative tasks on one event loop. A task yields control at await points, so blocking filesystem or CPU work can stall every task. Use asynchronous clients for large amounts of waiting I/O, retain task references, handle cancellation, and close clients with async context managers. Concurrency still needs a semaphore and an explicit scope limit.",
  "A queue separates producers from consumers and provides backpressure when bounded. Producers describe work; workers process it; a sentinel or queue shutdown policy signals completion. Every queued item needs a stable identity so retries do not duplicate evidence. Always acknowledge work in a finally block and collect exceptions into structured result records.",
  "A semaphore limits how many tasks enter a resource-sensitive section at once. It protects the lab service, local file descriptors, and memory; it is not merely a performance control. Combine a semaphore with rate limiting, per-operation timeouts, and a total job deadline. Measure active tasks to prove the bound is being enforced.",
  "Cancellation is a normal control path, not an exceptional crash. Code should stop accepting new work, cancel outstanding tasks, await their cleanup, flush completed evidence, and close files or clients. Context managers place cleanup beside acquisition. A resumable job writes checkpoints atomically so interruption cannot leave a half-valid state file.",
  "Machine-readable output should be preferred over terminal text. XML has elements, attributes, namespaces, and entity-related security concerns; JSON has objects, arrays, and primitive values. Disable unsafe external entity behavior, validate required fields, preserve the original tool version and command provenance, and translate outputs into one normalized internal schema.",
  "SQLite is an embedded relational database with transactions, constraints, indexes, and parameterized queries. Tables model entities, foreign keys model relationships, and unique constraints prevent duplicate evidence. Never interpolate values into SQL. Use transactions for related writes, store timestamps in a documented format, and index columns used by actual filtering queries.",
  "A resumable workflow separates immutable job configuration from mutable execution state. Each unit has pending, running, complete, or failed status plus attempt count and evidence reference. On restart, reconcile interrupted running work instead of blindly repeating it. Hash configuration and fixtures so a resumed report can prove it belongs to the same authorized job.",
  "HTML is a tree, not a regular language. Parse it with an HTML parser, resolve relative links against the authorized base URL, and distinguish forms, inputs, and navigation. Mapping an endpoint does not authorize submitting it. Default to passive extraction from saved fixtures and keep forms that change state behind a separate explicit approval control.",
  "A stateful HTTP workflow carries cookies, anti-CSRF values, and application state across requests. Model each transition with preconditions and expected results. Use a deliberately vulnerable lab account, redact session material, and reset fixtures after testing. Automation must stop when authentication state or scope differs from what the test case declares.",
  "Response comparison turns two observations into explainable differences. Compare status, selected headers, normalized body structure, and timing within tolerances; ignore volatile identifiers deliberately. A difference is evidence to investigate, not automatic proof of authorization failure. Store both test identities, request purpose, and expected policy decision.",
  "An authorization matrix lists subjects, resources, actions, and expected allow or deny decisions. Generate non-destructive cases from that matrix and execute only against a purpose-built lab. A good assertion explains expected policy and observed status without exposing another user's data. Denied tests are as important as allowed tests.",
  "Identity data forms a graph: users and hosts are nodes, while membership, ownership, and permission are directed edges. Normalize stable identifiers before joining sources and attach provenance to every edge. Graph reachability can reveal risky relationships, but the report must explain each contributing permission rather than present an opaque risk score.",
  "Windows evidence includes users, groups, services, scheduled tasks, registry configuration, ACLs, and event logs. Collection should use documented read-only APIs or commands and return typed records. Separate unavailable privileges from an absent finding, redact account secrets, and compare observations with a declared hardening baseline.",
  "Linux evidence includes accounts, groups, file modes, ownership, capabilities, services, scheduled jobs, and logs. Symlinks and mount boundaries can change what a path represents, so resolve cautiously and avoid following untrusted links during collection. Report configuration state and remediation guidance without attempting privilege escalation.",
  "Regression tests preserve a security fix by expressing the vulnerable behavior, corrected expectation, and safe fixture. Unit tests isolate pure decisions; integration tests use simulated services; property-based tests generate boundary inputs. A remediation test must fail for the known-bad fixture and pass for the corrected fixture without destructive payloads.",
  "An AI tool is a normal function behind a strict schema and policy boundary. Define typed arguments, a narrow description, structured success and error results, and an allowlisted implementation. The model may propose a call, but deterministic code validates scope, path, rate, timeout, and approval before execution. Start with local evidence-reading tools, not network actions.",
  "A provider-neutral agent loop separates planning, policy evaluation, tool execution, observation, and stopping. Keep conversation text out of direct command construction. Tool names come from a registry rather than dynamic imports, and every call receives a correlation ID. Bound steps and wall-clock time so a faulty plan cannot loop forever.",
  "Agent evaluation uses deterministic fixtures and expected decisions. Test whether the agent selects the right tool, supplies valid arguments, refuses out-of-scope requests, explains uncertainty, and stops after errors. Record latency, tool count, policy denials, and final evidence references. Performance optimization must never weaken authorization checks.",
  "A releasable local security agent needs packaging, configuration, logs, tests, documentation, and a threat model. The final framework should default to passive and dry-run modes, expose no arbitrary command tool, redact secrets, hash evidence, and make every action reviewable. A versioned release includes reproducible fixtures and mitigation retest examples.",
] as const;

const trackInstruction = {
  1: "Predict types, values, branches, and errors before running Python. Build explicit functions and domain models only after the underlying data flow is understood. Reusable deterministic Python—not model prompting—owns calculations and business rules.",
  2: "Work from small local campaign, goal, metric, or API-response fixtures. State the expected schema, normalize deliberately, retain rejected-record evidence, and keep secrets and customer data out of examples and logs.",
  3: "Place automation behind a narrow interface. Bound retries, time, pages, work items, and side effects; return structured success or failure; use mock connectors and dry-run before controlled integrations.",
  4: "Inspect the Git diff before staging. Separate semantic edits from line-ending-only changes, generated files, .DS_Store, secrets, and accidental text. Test and commit one learning outcome at a time.",
  5: "Express reliability and authorization as deterministic policy. Test allowed, denied, malformed, boundary, missing-data, and approval-required cases. Model output can propose but cannot override arithmetic, policy, budgets, or approval.",
  6: "Integrate only this week's vertical slice into MarketingOps AI. Define the input/output contract, trust boundary, acceptance tests, and evidence. Do not implement a later milestone early.",
  7: "Retrieve the week's concepts without notes. Complete a small blank-file task, explain one failure, connect the capability to the capstone, and record the next weak concept instead of adding new scope.",
} as const;

export function actualLessonSections(week: number, day: number, topic: string) {
  const preserved = week <= 2 || (week === 3 && day === 1);
  const technical = preserved
    ? weeklyTechnicalBriefs[week - 1]
    : `This lesson develops ${topic.toLowerCase()} as one bounded capability in the Autonomous MarketingOps system. Begin with a concrete input and expected output, identify malformed and boundary cases, and keep calculations and policy decisions in deterministic Python. Work from local fixtures or mock interfaces. If AI output is involved, treat it as untrusted proposed data: parse it into an explicit schema, reject invalid fields, and never route it directly to an external action. The implementation should expose useful failure information, preserve evidence identifiers, and remain small enough to test independently. Explain which component owns the behavior, which data crosses a trust boundary, and what later component may consume the result. The exercise is complete only when the student can rebuild the core behavior, test a normal case and a denied or failure case, and describe what this unlocks in MarketingOps AI without relying on a framework to hide the Python mechanics.`;
  return [
    { heading: "Technical lesson", content: technical },
    { heading: `How to practise ${topic}`, content: trackInstruction[day as keyof typeof trackInstruction] },
  ];
}
