"use client";
import Link from "next/link";
import { Lock, Star } from "lucide-react";
import { useApp } from "../../components/app-provider";
import { StatusBadge } from "../../components/course-panels";
import { PageSkeleton, ProgressNotice } from "../../components/progress-states";
import { capstoneMilestones } from "../../lib/course-view";
import { curriculumById } from "../../lib/curriculum";

const clean=(name:string,text:string)=>text.replace(new RegExp(`${name} for ${name}`,"gi"),name);

export default function CapstonePage(){const{state,loading,error,retry}=useApp();if(loading)return <PageSkeleton label="Loading capstone roadmap"/>;const items=capstoneMilestones(state);const currentIndex=Math.max(0,items.findIndex(item=>item.status!=="COMPLETED"));const completed=items.filter(item=>item.status==="COMPLETED").length;return <div className="page"><header className="page-header"><div><p className="eyebrow">Autonomous MarketingOps AI</p><h1>Capstone roadmap</h1><p>Deterministic foundations lead to bounded AI recommendations, policy checks, approval, controlled execution, and evidence.</p></div><div className="capstone-progress"><strong>{completed}/{items.length}</strong><span>milestones complete</span></div></header>{error&&<ProgressNotice message={error} retry={retry}/>}<div className="roadmap-progress" aria-label={`${completed} of ${items.length} capstone milestones complete`}><i style={{width:`${completed/items.length*100}%`}}/></div><ol className="capstone-roadmap">{items.map((item,index)=>{const weeks=[...new Set(item.lessonIds.map(id=>curriculumById.get(id)?.week).filter(Boolean))];const displayStatus=item.status==="COMPLETED"?"COMPLETED":index===currentIndex?"CURRENT":"LOCKED";return <li key={`${item.phase.number}-${item.name}`} className={index===currentIndex?"current":displayStatus.toLowerCase()}><span className="roadmap-marker">{displayStatus==="LOCKED"?<Lock aria-hidden="true"/>:<Star aria-hidden="true"/>}</span><article><div className="roadmap-heading"><div><p className="kicker">Milestone {index+1} · Phase {item.phase.number} · Week{weeks.length>1?"s":""} {weeks[0]}{weeks.length>1?`–${weeks.at(-1)}`:""}</p><h2>{item.name}</h2></div><StatusBadge status={displayStatus}/></div><p>{clean(item.name,item.deliverable)}</p><dl className="roadmap-meta"><div><dt>Depends on</dt><dd>{index?items[index-1].name:"Phase 0 mastery checkpoint"}</dd></div><div><dt>Capability unlocked</dt><dd>{item.capability}</dd></div></dl><details><summary>Associated lessons and acceptance criteria</summary><p>{item.lessonIds.map(id=>curriculumById.get(id)?.title).filter(Boolean).join(" · ")}</p><ul className="criteria-list">{item.criteria.map(criterion=><li key={criterion}>{criterion}</li>)}</ul></details><Link className="text-link" href={`/lessons/${item.lessonIds.at(-1)}`}>View milestone lesson</Link></article></li>})}</ol></div>}
