"use client";
import Link from "next/link";
import { Check, FolderGit2 } from "lucide-react";
import { useApp } from "../../components/app-provider";
import { StatusBadge } from "../../components/course-panels";
import { PageSkeleton, ProgressNotice } from "../../components/progress-states";
import { curriculumById } from "../../lib/curriculum";
import { projects, type ProjectView } from "../../lib/course-view";

function ProjectCard({project,featured=false}:{project:ProjectView;featured?:boolean}){return <article className={featured?"project-card featured":"project-card"}><div className="project-title"><FolderGit2 aria-hidden="true"/><div><p className="kicker">{featured?"Active project":"Project"}</p><h3>{project.name}</h3><p>{project.milestone}</p></div><StatusBadge status={project.status}/></div><h4>Acceptance evidence</h4><ul className="criteria-list">{project.tests.map(item=><li key={item}><Check aria-hidden="true"/>{item}</li>)}</ul><details><summary>Lessons and repository details</summary><div className="project-links">{project.lessonIds.map(id=><Link className="text-link" href={`/lessons/${id}`} key={id}>{curriculumById.get(id)?.title??id}</Link>)}</div><code>{project.path??"Created during its scheduled lesson"}</code><p>{project.lessonIds.map(id=>curriculumById.get(id)&&id).filter(Boolean).length} associated lesson{project.lessonIds.length===1?"":"s"}</p></details></article>}

export default function ProjectsPage(){const{state,loading,error,retry}=useApp();if(loading)return <PageSkeleton label="Loading projects"/>;const all=projects(state);const active=all.filter(item=>item.status==="IN PROGRESS");const completed=all.filter(item=>item.status==="COMPLETED");const foundation=all.slice(0,3).filter(item=>item.status!=="IN PROGRESS"&&item.status!=="COMPLETED");const upcoming=all.slice(3).filter(item=>item.status==="NOT STARTED");return <div className="page"><header className="page-header"><div><p className="eyebrow">Portfolio evidence</p><h1>Projects</h1><p>Statuses come from canonical progress records—never from files merely existing in the repository.</p></div></header>{error&&<ProgressNotice message={error} retry={retry}/>}<ProjectGroup title="Active project" items={active} featured/><ProjectGroup title="Completed foundation work" items={completed}/>{foundation.length>0&&<ProjectGroup title="Foundation work" items={foundation}/>}<ProjectGroup title="Upcoming MarketingOps projects" items={upcoming}/></div>}
function ProjectGroup({title,items,featured=false}:{title:string;items:ProjectView[];featured?:boolean}){if(!items.length)return null;return <section className="project-group"><div className="section-heading"><h2>{title}</h2><span>{items.length}</span></div><div className="project-grid">{items.map(project=><ProjectCard key={project.name} project={project} featured={featured}/>)}</div></section>}
