"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useApp } from "../../components/app-provider";
import { StatusBadge } from "../../components/course-panels";
import { PageSkeleton, ProgressNotice } from "../../components/progress-states";
import { curriculumById } from "../../lib/curriculum";
import { masteryStates, skillMastery, skills } from "../../lib/course-view";

const domain=(name:string)=>["Python Core","Functions","Loops","CSV / JSON"].includes(name)?"Python foundations":["Testing","Git"].includes(name)?"Engineering practice":["HTTP & APIs","FastAPI","Databases"].includes(name)?"Application engineering":"AI systems";

export default function SkillsPage(){const{state,loading,error,retry}=useApp();const[filter,setFilter]=useState("ALL");const rows=useMemo(()=>skills.map(skill=>({...skill,mastery:skillMastery(state,skill.lessons)})).filter(skill=>filter==="ALL"||skill.mastery===filter),[state,filter]);if(loading)return <PageSkeleton label="Loading skill mastery"/>;const counts=masteryStates.map(status=>({status,count:skills.filter(skill=>skillMastery(state,skill.lessons)===status).length}));return <div className="page"><header className="page-header"><div><p className="eyebrow">Competency evidence</p><h1>Skills and mastery</h1><p>Lesson completion records progress. Mastery records what evidence shows you can use independently.</p></div></header>{error&&<ProgressNotice message={error} retry={retry}/>}<section className="mastery-summary" aria-label="Mastery summary">{counts.map(item=><button key={item.status} className={filter===item.status?"active":""} onClick={()=>setFilter(filter===item.status?"ALL":item.status)} aria-pressed={filter===item.status}><strong>{item.count}</strong><span>{item.status}</span></button>)}</section>{["Python foundations","Engineering practice","Application engineering","AI systems"].map(group=>{const grouped=rows.filter(skill=>domain(skill.name)===group);if(!grouped.length)return null;return <section className="skill-domain" key={group}><h2>{group}</h2><div className="skill-table" role="list">{grouped.map(skill=>{const evidence=skill.lessons.map(id=>state.progress[id]).filter(Boolean);return <article role="listitem" key={skill.name}><div className="skill-title"><h3>{skill.name}</h3><StatusBadge status={skill.mastery}/></div><div className="mastery-path" aria-label={`${skill.name} mastery path`}>{["INTRODUCED","PRACTICED","ASSESSED","MASTERED"].map(stage=><span key={stage} className={skill.mastery===stage?"current":masteryStates.indexOf(skill.mastery)>masteryStates.indexOf(stage as typeof masteryStates[number])?"done":""}>{stage}</span>)}</div><details><summary>Supporting lessons and projects</summary>{skill.lessons.map(id=>{const lesson=curriculumById.get(id);return lesson?<Link className="text-link" href={`/lessons/${id}`} key={id}>{lesson.title}</Link>:null})}<p><strong>Projects:</strong> {skill.projects.length?skill.projects.join(" · "):"No project evidence mapped yet"}</p></details>{evidence.length?<details><summary>Evidence ({evidence.length})</summary><ul>{evidence.map(item=><li key={item.lessonId}><strong>{item.state}</strong> · {curriculumById.get(item.lessonId)?.title}<small>{item.completedAt?new Date(item.completedAt).toLocaleDateString():item.startedAt?`Started ${new Date(item.startedAt).toLocaleDateString()}`:"No date"}{item.score!==null?` · Score ${item.score}%`:""}</small></li>)}</ul></details>:<p className="compact-empty">No stored evidence yet.</p>}</article>})}</div></section>})}</div>}
