import { describe, expect, it } from "vitest";
import { curriculum, lessonSchema, validateCurriculum } from "../lib/curriculum";

describe("curriculum", () => {
  it("contains 36 complete seven-day weeks", () => { expect(validateCurriculum()).toHaveLength(252); expect(new Set(curriculum.map(l=>l.week)).size).toBe(36); for(let week=1;week<=36;week++){const days=curriculum.filter(l=>l.week===week);expect(days.filter(l=>l.required)).toHaveLength(6);expect(days.filter(l=>!l.required)).toHaveLength(1);} });
  it("has unique IDs and valid prerequisites", () => { const ids=new Set(curriculum.map(l=>l.id)); expect(ids.size).toBe(252); curriculum.flatMap(l=>l.prerequisiteLessonIds).forEach(id=>expect(ids.has(id)).toBe(true)); });
  it("validates every record and official URL", () => { curriculum.forEach(l=>{expect(()=>lessonSchema.parse(l)).not.toThrow();l.officialResources.forEach(r=>expect(()=>new URL(r.url)).not.toThrow())}); });
  it("contains no placeholder language", () => { const serialized=JSON.stringify(curriculum).toLowerCase(); ["content coming soon","add lesson here","lorem ipsum"].forEach(term=>expect(serialized).not.toContain(term)); });
  it("preserves the checkpoint and builds toward MarketingOps AI", () => { expect(curriculum.find(l=>l.id==="week-03-day-01")?.guidedExamples[0].code).toContain("max_attempts + 1"); expect(curriculum.find(l=>l.id==="week-03-day-06")?.title).toContain("Campaign Rules Checker"); expect(curriculum.find(l=>l.id==="week-23-day-06")?.title).toContain("AI Performance Analyst"); expect(curriculum.find(l=>l.id==="week-36-day-06")?.title).toContain("Autonomous MarketingOps"); });
  it("records prohibited migration shortcuts", () => { const adapted=curriculum.filter(l=>l.week>=3); expect(adapted.every(l=>l.sourceBasis.excludedMaterial.some(x=>x.includes("unrestricted model-to-action")))).toBe(true); });
  it("provides distinct substantive teaching content for every calendar lesson", () => { const bodies=curriculum.map(l=>l.conceptSections.map(s=>s.content).join("\n")); expect(new Set(bodies).size).toBe(252); bodies.forEach(body=>expect(body.length).toBeGreaterThan(500)); curriculum.filter(l=>l.required).forEach(l=>{expect(l.guidedExamples[0].code.length).toBeGreaterThan(80);expect(l.practiceExercises.length).toBeGreaterThanOrEqual(2);expect(l.knowledgeCheck.length).toBeGreaterThanOrEqual(2)}); });
  it("uses lesson-specific approved official sources", () => { const allowed=new Set(["docs.python.org","www.gnu.org","learn.microsoft.com","git-scm.com","docs.github.com","owasp.org","cheatsheetseries.owasp.org","portswigger.net","developer.mozilla.org"]);curriculum.filter(l=>l.required).forEach(l=>{expect(l.officialResources.length).toBeGreaterThan(0);l.officialResources.forEach(r=>expect(allowed.has(new URL(r.url).hostname)).toBe(true))});expect(new Set(curriculum.flatMap(l=>l.officialResources.map(r=>r.url))).size).toBeGreaterThan(40); });
  it("keeps deterministic analysis ahead of LLM integration", () => { const kpi=curriculum.findIndex(l=>l.id==="week-06-day-01"); const model=curriculum.findIndex(l=>l.id==="week-20-day-01"); const policy=curriculum.findIndex(l=>l.id==="week-28-day-01"); expect(kpi).toBeGreaterThan(0); expect(model).toBeGreaterThan(kpi); expect(policy).toBeGreaterThan(model); });
});
